// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSh-zm33FXlm1EYgnTKQdFOiM4EbHMzmw',
    appId: '1:991544146903:web:7f199105eb92e605e12992',
    messagingSenderId: '991544146903',
    projectId: 'bingo-game-e57bf',
    authDomain: 'bingo-game-e57bf.firebaseapp.com',
    storageBucket: 'bingo-game-e57bf.firebasestorage.app',
    measurementId: 'G-LE8NKWMWYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZP-sZ2AHzZ5O1UeKAGGYTPMQLizSZRY',
    appId: '1:991544146903:android:232b8a47aef0bf70e12992',
    messagingSenderId: '991544146903',
    projectId: 'bingo-game-e57bf',
    storageBucket: 'bingo-game-e57bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnmutnsFSBCquNirTBLsOcPtlIXsOX-0',
    appId: '1:991544146903:ios:b6988947d39af280e12992',
    messagingSenderId: '991544146903',
    projectId: 'bingo-game-e57bf',
    storageBucket: 'bingo-game-e57bf.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfnmutnsFSBCquNirTBLsOcPtlIXsOX-0',
    appId: '1:991544146903:ios:b6988947d39af280e12992',
    messagingSenderId: '991544146903',
    projectId: 'bingo-game-e57bf',
    storageBucket: 'bingo-game-e57bf.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSh-zm33FXlm1EYgnTKQdFOiM4EbHMzmw',
    appId: '1:991544146903:web:e2a6ed0b52438134e12992',
    messagingSenderId: '991544146903',
    projectId: 'bingo-game-e57bf',
    authDomain: 'bingo-game-e57bf.firebaseapp.com',
    storageBucket: 'bingo-game-e57bf.firebasestorage.app',
    measurementId: 'G-P03S6L7WJ3',
  );
}
