// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfuaExoddJk2OybgJSeBxxLc9NtjfzzwY',
    appId: '1:129782074914:web:d0d0fc8e7dc6e9afeac47b',
    messagingSenderId: '129782074914',
    projectId: 'bingo-83cb4',
    authDomain: 'bingo-83cb4.firebaseapp.com',
    storageBucket: 'bingo-83cb4.firebasestorage.app',
    measurementId: 'G-KG1XRKHRLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnta1s6G64vnibQ5NuxZa5J3Sc46qBqw',
    appId: '1:129782074914:android:af41dc63d93fef51eac47b',
    messagingSenderId: '129782074914',
    projectId: 'bingo-83cb4',
    storageBucket: 'bingo-83cb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRjFTRtRX2n9VCz1THKX39VLlPG6C72kA',
    appId: '1:129782074914:ios:1dd77b273f769c39eac47b',
    messagingSenderId: '129782074914',
    projectId: 'bingo-83cb4',
    storageBucket: 'bingo-83cb4.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRjFTRtRX2n9VCz1THKX39VLlPG6C72kA',
    appId: '1:129782074914:ios:1dd77b273f769c39eac47b',
    messagingSenderId: '129782074914',
    projectId: 'bingo-83cb4',
    storageBucket: 'bingo-83cb4.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfuaExoddJk2OybgJSeBxxLc9NtjfzzwY',
    appId: '1:129782074914:web:84ba4ee0e7dc96b1eac47b',
    messagingSenderId: '129782074914',
    projectId: 'bingo-83cb4',
    authDomain: 'bingo-83cb4.firebaseapp.com',
    storageBucket: 'bingo-83cb4.firebasestorage.app',
    measurementId: 'G-RFYSYJ6H2H',
  );
}
